### ISSUE TITLE
Windspeed 0 shows invalid

### ISSUE THREAD

**Issue by UweLoyal** [tomvanswam/compass-card#778] opened 2023-02-08 21:58 UTC
If windspeed is 0 invalid is shown

![image](https://user-images.githubusercontent.com/5464553/217660590-7d27705e-c10d-42d6-b97f-8c96fa12eb5d.png)

**Comment by tomvanswam** [comment] 2023-02-10 19:01
Could you post the card's config, and a screenshot of the developertools, states page, filtered for one of the value_sensors configured in the card?

**Comment by UweLoyal** [comment] 2023-02-11 18:12
type: custom:compass-card
indicator_sensors:
  - sensor: input_number.Test_Windrichtung
    indicator:
      type: arrow_inward
      color: red
value_sensors:
  - sensor: sensor.Test_Windgeschwindigkeit
    decimals: 1
  - sensor: sensor.Test_Windboeengeschwindigkeit
    decimals: 1
compass:
  circle: null
  east:
    show: true
  west:
    show: true
  south:
    show: true
  north:
    show: true
  language: de
__________________________________________________________________

![image](https://user-images.githubusercontent.com/5464553/218273957-672a0260-ed83-4f88-8d3e-1c87ca8896d6.png)

![image](https://user-images.githubusercontent.com/5464553/218274271-d85fa8da-62c7-4de5-8788-01a92f5710da.png)

![image](https://user-images.githubusercontent.com/5464553/218274018-1c6e52cd-f16d-4201-91ba-da84d85d5ad8.png)

Working now with a trick, adding 0.001 to value!
;-)

Rgds
   Uwe

**Comment by tomvanswam** [comment] 2023-02-12 18:41
Thanks, if possible, please screenshot this Home-Assistant page (see my screenshot below)
Which shows the following sensors at the moment the card shows invalid:
* sensor.Test_Windgeschwindigkeit
* sensor.Test_Windboeengeschwindigkeit
![image](https://user-images.githubusercontent.com/2330034/218330253-d81f111f-ad84-46e6-a0c2-a58c9de3a6ee.png)

P.S. I edited you post to format the yaml config.

**Comment by UweLoyal** [comment] 2023-02-12 20:38
For your Info, I‘m using ioBroker!

**Comment by UweLoyal** [comment] 2023-02-14 18:14
In ioBroker you can see in objects the 0 instead of invalid.
Send you above.

![image](https://user-images.githubusercontent.com/5464553/218822505-72623745-bd22-4480-9ecd-7278fae8cabe.png)

**Comment by tomvanswam** [comment] 2023-02-14 19:40
> For your Info, I‘m using ioBroker!

So if I'm understanding correctly, you're using ioBroker with something like [lovelace adapter for ioBroker](https://github.com/ioBroker/ioBroker.lovelace) and added the compass-card to that?

I pinpointed the bug, this is only happening when you add a configuration option for a sensor.
When you remove the `decimals: 1` line the card will show 0. However then you might end up with more decimals then you'd like.

**Comment by UweLoyal** [comment] 2023-02-14 20:50
When removing decimals: 1 you will get an uprounded value!
0,4 km/h --> 1 km/h
The problem is ony the 0 !

**Comment by tomvanswam** [comment] 2023-02-14 22:48
I understand.

In my dashboard the 0 value works, so I could not figure out why it was not working for you. But I am not rounding the value and then it shows 0, so the bug is somewhere in dealing with the decimals, or even other configuration settings beloning to the sensor that has value 0. 

Bug is noted and I'll look into finding a fix.

**Comment by tomvanswam** [comment] 2023-09-14 19:31
I'm not able to reproduce this. So I will close this issue.

**Closed by tomvanswam** 2023-09-14 19:31 UTC
Labels: bug
