### ISSUE TITLE
GUI editor not working

### ISSUE THREAD

**Issue by SteveRMann** [tomvanswam/compass-card#588] opened 2022-07-16 22:49 UTC
**Checklist:**

- [ ] I updated to the latest version available
I just installed the card a few weeks ago.

- [ ] I cleared the cache of my browser
done, even tried another browser.

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Chrome and Opera, Windows 10

Rather than retyping everything, please look at: 
[https://community.home-assistant.io/t/bug-editing-custom-compass-card/440836](https://community.home-assistant.io/t/bug-editing-custom-compass-card/440836)

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
https://community.home-assistant.io/t/bug-editing-custom-compass-card/440836

**Comment by tomvanswam** [comment] 2022-07-17 17:19
Duplicate of #464.

Due to unforseen personal circumstances it will take some time for me to address this issue.

**Closed** 2022-08-04 13:19 UTC
Labels: bug
